tags:
  - name: 'User'
    description: 'User API'

paths:
  /user/register:
    post:
      tags:
        - User
      summary: 'Register a new user'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSchema'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserSchema'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
        '500':
          description: 'Server Internal Error'
  /user/login:
    post:
      tags:
        - User
      summary: 'login user'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSchema'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserSchema'
      responses:
        '200':
          description: User login successfully
        '400':
          description: Invalid input
        '500':
          description: 'Server Internal Error'
  /user/logout:
    post:
      tags:
        - User
      summary: 'logout user'
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutSchema'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LogoutSchema'
      responses:
        '200':
          description: User logout successfully
        '400':
          description: Invalid input
        '500':
          description: 'Server Internal Error'
  /user/get-user/{username}:
    get:
      tags:
        - User
      summary: 'get User with username'
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          example: 'johndoe'
      responses:
        '200':
          description: 'User find successfully'
        '400':
          description: 'Invalid input'
        '500':
          description: 'Server Internal Error'

components:
  schemas:
    UserSchema:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: johndoe
        password:
          type: string
          example: secret123
    LogoutSchema:
      type: object
      required:
        - id
      properties:
        id:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
