tags:
  - name: 'Rooms'
    description: 'Rooms API'

components:
  schemas:
    RolesEnum:
      type: string
      enum:
        - ADMIN
        - USER
    CreateRoom:
      type: object
      required:
        - name
        - convId
      properties:
        name:
          type: string
        convId:
          type: string
        description:
          type: string
        role:
          $ref: '#/components/schemas/RolesEnum'
    UdpateRoom:
      type: object
      required:
        - id
      properties:
        name:
          type: string
        id:
          type: string
        description:
          type: string
        role:
          $ref: '#/components/schemas/RolesEnum'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /room/create:
    post:
      tags:
        - Rooms
      summary: create room api
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoom'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateRoom'
      responses:
        201:
          description: 'Create Room Successfully'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Internal Error'
  /room/update:
    put:
      tags:
        - Rooms
      summary: 'update Room'
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UdpateRoom'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UdpateRoom'
      responses:
        200:
          description: 'Update Room Successfully'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Internal Error'
  /room/delete/{id}:
    delete:
      tags:
        - Rooms
      summary: 'Delete Room'
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'Delete Room Successfully'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Internal Error'
  /room/get/{id}:
    get:
      tags:
        - Rooms
      summary: 'Get Room'
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'Get Room Successfully'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Internal Error'
